class FeedbackClusteringError(Exception): ...
class IngestionError(FeedbackClusteringError): ...
class EmbeddingError(FeedbackClusteringError): ...
class ClusteringError(FeedbackClusteringError): ...
class LabelingError(FeedbackClusteringError): ...
class ConfigurationError(FeedbackClusteringError): ...
class UserCancelledError(FeedbackClusteringError): ...
